# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1848, 1017)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.irVideo = QtWidgets.QLabel(self.centralwidget)
        self.irVideo.setGeometry(QtCore.QRect(10, 10, 576, 324))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.irVideo.setFont(font)
        self.irVideo.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.irVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.irVideo.setObjectName("irVideo")
        self.rgbVideo = QtWidgets.QLabel(self.centralwidget)
        self.rgbVideo.setGeometry(QtCore.QRect(10, 683, 576, 324))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.rgbVideo.setFont(font)
        self.rgbVideo.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.rgbVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.rgbVideo.setObjectName("rgbVideo")
        self.logText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logText.setGeometry(QtCore.QRect(1438, 10, 400, 1001))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.logText.setFont(font)
        self.logText.setUndoRedoEnabled(False)
        self.logText.setReadOnly(True)
        self.logText.setObjectName("logText")
        self.irIP = QtWidgets.QLineEdit(self.centralwidget)
        self.irIP.setGeometry(QtCore.QRect(600, 10, 250, 25))
        self.irIP.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.irIP.setClearButtonEnabled(False)
        self.irIP.setObjectName("irIP")
        self.irConnect = QtWidgets.QPushButton(self.centralwidget)
        self.irConnect.setEnabled(True)
        self.irConnect.setGeometry(QtCore.QRect(600, 40, 100, 25))
        self.irConnect.setObjectName("irConnect")
        self.irDisconnect = QtWidgets.QPushButton(self.centralwidget)
        self.irDisconnect.setEnabled(False)
        self.irDisconnect.setGeometry(QtCore.QRect(600, 70, 100, 25))
        self.irDisconnect.setObjectName("irDisconnect")
        self.irFull = QtWidgets.QPushButton(self.centralwidget)
        self.irFull.setGeometry(QtCore.QRect(600, 304, 30, 30))
        self.irFull.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("assets/icons/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.irFull.setIcon(icon)
        self.irFull.setObjectName("irFull")
        self.thermalFull = QtWidgets.QPushButton(self.centralwidget)
        self.thermalFull.setGeometry(QtCore.QRect(600, 641, 30, 30))
        self.thermalFull.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icons/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.thermalFull.setIcon(icon1)
        self.thermalFull.setObjectName("thermalFull")
        self.thermalIP = QtWidgets.QLineEdit(self.centralwidget)
        self.thermalIP.setGeometry(QtCore.QRect(600, 347, 250, 25))
        self.thermalIP.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.thermalIP.setClearButtonEnabled(False)
        self.thermalIP.setObjectName("thermalIP")
        self.thermalDisconnect = QtWidgets.QPushButton(self.centralwidget)
        self.thermalDisconnect.setEnabled(False)
        self.thermalDisconnect.setGeometry(QtCore.QRect(600, 407, 100, 25))
        self.thermalDisconnect.setObjectName("thermalDisconnect")
        self.thermalConnect = QtWidgets.QPushButton(self.centralwidget)
        self.thermalConnect.setGeometry(QtCore.QRect(600, 377, 100, 25))
        self.thermalConnect.setObjectName("thermalConnect")
        self.irMinimize = QtWidgets.QPushButton(self.centralwidget)
        self.irMinimize.setEnabled(True)
        self.irMinimize.setGeometry(QtCore.QRect(1810, 980, 30, 30))
        self.irMinimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("assets/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.irMinimize.setIcon(icon2)
        self.irMinimize.setObjectName("irMinimize")
        self.thermalMinimize = QtWidgets.QPushButton(self.centralwidget)
        self.thermalMinimize.setEnabled(True)
        self.thermalMinimize.setGeometry(QtCore.QRect(1810, 980, 30, 30))
        self.thermalMinimize.setText("")
        self.thermalMinimize.setIcon(icon2)
        self.thermalMinimize.setObjectName("thermalMinimize")
        self.thermalVideo = QtWidgets.QLabel(self.centralwidget)
        self.thermalVideo.setGeometry(QtCore.QRect(10, 347, 576, 324))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.thermalVideo.setFont(font)
        self.thermalVideo.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.thermalVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.thermalVideo.setObjectName("thermalVideo")
        self.rgbFull = QtWidgets.QPushButton(self.centralwidget)
        self.rgbFull.setGeometry(QtCore.QRect(600, 977, 30, 30))
        self.rgbFull.setText("")
        self.rgbFull.setIcon(icon)
        self.rgbFull.setObjectName("rgbFull")
        self.rgbDisconnect = QtWidgets.QPushButton(self.centralwidget)
        self.rgbDisconnect.setEnabled(False)
        self.rgbDisconnect.setGeometry(QtCore.QRect(600, 743, 100, 25))
        self.rgbDisconnect.setObjectName("rgbDisconnect")
        self.rgbIP = QtWidgets.QLineEdit(self.centralwidget)
        self.rgbIP.setGeometry(QtCore.QRect(600, 683, 250, 25))
        self.rgbIP.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rgbIP.setClearButtonEnabled(False)
        self.rgbIP.setObjectName("rgbIP")
        self.rgbConnect = QtWidgets.QPushButton(self.centralwidget)
        self.rgbConnect.setGeometry(QtCore.QRect(600, 713, 100, 25))
        self.rgbConnect.setObjectName("rgbConnect")
        self.rgbMinimize = QtWidgets.QPushButton(self.centralwidget)
        self.rgbMinimize.setEnabled(True)
        self.rgbMinimize.setGeometry(QtCore.QRect(1810, 980, 30, 30))
        self.rgbMinimize.setText("")
        self.rgbMinimize.setIcon(icon2)
        self.rgbMinimize.setObjectName("rgbMinimize")
        self.irProcess = QtWidgets.QPushButton(self.centralwidget)
        self.irProcess.setGeometry(QtCore.QRect(600, 100, 100, 25))
        self.irProcess.setObjectName("irProcess")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.irVideo.setText(_translate("MainWindow", "NO VIDEO AVAILABLE"))
        self.rgbVideo.setText(_translate("MainWindow", "NO VIDEO AVAILABLE"))
        self.irConnect.setText(_translate("MainWindow", "Connect"))
        self.irDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.thermalDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.thermalConnect.setText(_translate("MainWindow", "Connect"))
        self.thermalVideo.setText(_translate("MainWindow", "NO VIDEO AVAILABLE"))
        self.rgbDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.rgbConnect.setText(_translate("MainWindow", "Connect"))
        self.irProcess.setText(_translate("MainWindow", "Process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
